<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="GGKU4SYS199" name="com.ggk.orangehrm.AddVerifyUser" tests="1" failures="1" timestamp="09 Jul 2019 10:13:39 GMT" time="105.044" errors="0">
  <testcase name="addVerify" time="105.044" classname="com.ggk.orangehrm.AddVerifyUser">
    <failure type="java.lang.AssertionError" message="expected [] but found [hema]">
      <![CDATA[java.lang.AssertionError: expected [] but found [hema]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertEqualsImpl(Assert.java:137)
at org.testng.Assert.assertEquals(Assert.java:118)
at org.testng.Assert.assertEquals(Assert.java:453)
at org.testng.Assert.assertEquals(Assert.java:463)
at com.ggk.applicationLibrary.HrmApplicationLibrary.verify(HrmApplicationLibrary.java:110)
at com.ggk.orangehrm.AddVerifyUser.addVerify(AddVerifyUser.java:18)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
at java.lang.reflect.Method.invoke(Unknown Source)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at java.util.concurrent.ThreadPoolExecutor.runWorker(Unknown Source)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(Unknown Source)
at java.lang.Thread.run(Unknown Source)
]]>
    </failure>
  </testcase> <!-- addVerify -->
</testsuite> <!-- com.ggk.orangehrm.AddVerifyUser -->
